name: health-checkin

on:
  schedule:
    - cron:  ${random.int[10,50]} 0 * * * 
      # 
      # https://tool.lu/crontab/ 
  workflow_dispatch:  

jobs:
  checkin:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html

    steps:
    - uses: actions/checkout@v2

    - name: Download Script
      run: |
        wget https://raw.githubusercontent.com/Zwysun/HealthCheckin/main/hitcarder.py -O checkin.py

    - name: Install Python
      run: |
        sudo apt update && \
        sudo apt install python3
      
    - name: Install requirements
      run: |
        pip3 install -r requirements.txt
       # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Checkin
      run: |
        python3 checkin.py 
      env: 
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        PUSH_KEY: ${{ secrets.PUSH_KEY }}
        PUSH_SECRET: ${{ secrets.PUSH_SECRET }}
        
